### ISSUE TITLE
Make Mission one-click-portable

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_OnTheFly.Desert_E#18]
Add Spawn Coordinates in [adjustInitialSpawnPosition.sqf](https://github.com/gruppe-adler/TvT_OnTheFly.Desert_E/blob/master/mission_setup/adjustInitialSpawnPosition.sqf):

- [x] Chernarus Summer
- [x] Takistan
- [x] Altis
- [x] Stratis
- [x] Bornholm
- [x] Panthera
- [x] Sahrani
- [x] Bystrica
- [x] Capraia
- [x] Zargabad
- [x] Thirsk
- [x] Podagorsk
- [x] Shapur
- [x] X-Cam Prototype
- [x] Clafghan
- [x] Fatah
- [x] Sarugao
- [x] Chernarus

**Comment by nomisum** [comment]
Some Maps still missing in adjustInitialSpawnPosition.sqf

**Comment by nomisum** [comment]
added a bunch of cool maps

**Comment by AdlerXiviD** [comment]
Chernarus should have the same coordinates as Chernarus -Summer.

**Comment by nomisum** [comment]
good catch smarty ^^
