### ISSUE TITLE
add possibility to select uniform independent from other side

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_OnTheFly.Desert_E#39]
combination easter - tropentarn should be possible

**Comment by AdlerXiviD** [comment]
Will be possible if VA is implemented (which is already done) or do you want an ingame option for the whole team? Like a box (yes another box) with an option "Change Outfit"?

**Comment by nomisum** [comment]
I assume it should be free for all to decide on the VA. We should actually leave the preset parameter intact, so no one has to spawn nude. 

Changable outfits triggered from one person will result in significant workload with loads of testing and possible locality issues.

**Comment by nomisum** [comment]
closing this as provided in VA
